- name: set roundcube password
  command: psql -d {{ webmail_db_database }} -c "ALTER USER {{ webmail_db_username }} with password '{{ webmail_db_password }}';"
  become_user: "{{ db_admin_username }}"
  notify: import sql carddav

- name: import sql carddav
  action: shell PGPASSWORD='{{ webmail_db_password }}' psql -h localhost -d {{ webmail_db_database }} -U {{ webmail_db_username }} -f /var/lib/roundcube/plugins/carddav/dbinit/postgres.sql

- name: install passwd function
  command: psql -d {{ mail_db_database }} -f /etc/postfix/update_passwd.sql
  become_user: "{{ db_admin_username }}"
