---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  become: True
  gather_facts: True
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'testing' if testing is defined else 'user' }}.yml
    - vars/private.yml

  roles:
    - { role: common, tags: common }
    - { role: mailserver, tags: mailserver }
    # - { role: postfixadmin, tags: postfixadmin }
    - { role: webmail, tags: webmail }
    - { role: blog, tags: blog }
    - { role: ircbouncer, tags: ircbouncer }
    - { role: xmpp, tags: xmpp }
    - { role: owncloud, tags: owncloud }
    - { role: vpn, tags: vpn }
    - { role: tarsnap, tags: tarsnap }
    - { role: news, tags: news }
    - { role: git, tags: git }
    - { role: newebe, tags: newebe }
    - { role: readlater, tags: readlater }
    - { role: monitoring, tags: monitoring }  # Monitoring role should be last. See roles/monitoring/README.md
