---
# Defines handlers applicable across all machines in the infrastructure.

- name: restart ntp
  service: name=ntp state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart ssh
  service: name=ssh state=restarted
